function data = import_oai_tcp_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UE1018CUBICFIRST100SECDL24PRBV1 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  UE1018CUBICFIRST100SECDL24PRBV1 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  UE1018cubicfirst100secDL24prbv1 = importfile("/Users/salvo/PycharmProjects/tcp_wireless_kpi/1UE_1018_cubic_first_100sec_DL_24prb/1UE_1018_cubic_first_100sec_DL_24prb_v1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jun-2023 23:00:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 41);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["tmbuf", "RNTI", "UENum", "ul_thr_ue", "dl_thr_ue", "ph", "pcmax", "avg_rsrp", "num_rsrp_meas", "cqi", "pucch_snrx10", "pusch_snrx10", "raw_rssi", "ri1", "pmi_x1", "pmi_x2", "dlerrors", "pucch0_DTX", "dl_bler_statsbler", "dl_bler_statsmcs", "dltotal_bytes", "ulsch_DTX", "ulerrors", "ul_bler_statsbler", "ul_bler_statsmcs", "ulsch_total_bytes_scheduled", "ultotal_bytes", "dlrounds", "ulrounds", "cwnd_values", "inflight", "rtt", "sending_rate", "throughput", "retransmissions_interval", "cwnd_values1", "inflight1", "rtt1", "sending_rate1", "throughput1", "retransmissions_interval1"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["dlrounds", "ulrounds"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["dlrounds", "ulrounds"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "tmbuf", "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, "RNTI", "TrimNonNumeric", true);
opts = setvaropts(opts, "RNTI", "ThousandsSeparator", ",");

% Import the data
data = readtable(filename, opts);

end